# Dockerfile.marrtinorobot2
FROM marrtinorobot2:system

LABEL maintainer="ferrarini09@gmail.com"

# Variabile di distribuzione
ENV ROS_DISTRO=humble

USER root
RUN apt-get update -q && \
    apt-get install -y \
    mpg321 sox  libttspico-utils 

RUN pip3 install gtts opencv-python opencv-python-headless


# Installazione di pacchetti e repository MARRtino
RUN mkdir -p /home/ubuntu/marrtinorobot2_ws/src && \
    mkdir -p /home/ubuntu/src && \
    cd /home/ubuntu/src && \
    git clone https://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@github.com/artigianitecnologici/marrtinorobot2.git && \
    git clone https://github.com/robo-friends/m-explore-ros2.git
        # git clone https://github.com/orbbec/OrbbecSDK_ROS2.git && \
        #git clone -b ${ROS_DISTRO} https://github.com/micro-ROS/micro_ros_setup.git /home/ubuntu/marrtinorobot2_ws/src/micro_ros_setup && \

WORKDIR /home/ubuntu/marrtinorobot2_ws/src
RUN ln -s /home/ubuntu/src/DynamixelSDK . && \
    ln -s /home/ubuntu/src/dynamixel-workbench-msgs . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_base . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_bringup . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_description . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_webinterface . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_navigation . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_vision . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_voice . && \
    ln -s /home/ubuntu/src/marrtinorobot2/marrtinorobot2_cartographer . && \
    ln -s /home/ubuntu/src/m-explore-ros2/explore .

# Configurazione finale per l'utente 'ubuntu'
WORKDIR /home/ubuntu/marrtinorobot2_ws
RUN rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y

RUN source /opt/ros/$ROS_DISTRO/setup.bash \
    && colcon build
#RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
# RUN colcon build && \
#     source /home/ubuntu/marrtinorobot2_ws/install/setup.bash

RUN echo "source /home/ubuntu/marrtinorobot2_ws/install/setup.bash" >> /home/ubuntu/.bashrc && \
    echo "export MARRTINOROBOT2_BASE=2wd" >> /home/ubuntu/.bashrc && \
    echo "export MARRTINOROBOT2_LASER_SENSOR=rplidar" >> /home/ubuntu/.bashrc && \
    echo "export MARRTINOROBOT2_DEPTH_SENSOR=oakdlite" >> /home/ubuntu/.bashrc && \
    echo "export MARRTINOROBOT2_WEBI=$HOME/src/marrtinorobot2/marrtinorobot2_webinterface/www" >> $HOME/.bashrc && \
    echo "export MARRTINOROBOT2_WS=$HOME/marrtinorobot2_ws" >> $HOME/.bashrc && \
    echo "alias cdmd='cd ~/src/marrtinorobot2/docker'" >> $HOME/.bashrc && \
    echo "alias cdm='cd ~/src/marrtinorobot2'" >> $HOME/.bashrc && \
    echo "alias cb='cd ~/marrtinorobot2 && colcon build'" >> $HOME/.bashrc

#
CMD [ "/bin/bash", "-ci", "/home/ubuntu/src/marrtinorobot2/bringup/1-bringup.bash" ]

