services:

  webgui:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "${MARRTINOROBOT2_WEBI}/www:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php

  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "${MARRTINOROBOT2_WEBI}/www:/var/www/html"

  ros2:
    image: marrtinorobot2:ros2
    container_name: Dockerfile.ros2
    ports:
      - "8085:80"
    security_opt:
      - seccomp=unconfined
    shm_size: "512m"
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - $MARRTINOROBOT2_HOME:/home/ubuntu/src/marrtinorobot2
      - /dev:/dev
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    dns: 8.8.8.8
    networks:
      - nginx-network
    privileged: true
    tty: true
    stdin_open: true
    restart: always


networks:
  nginx-network:
    driver: bridge
