version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
