version: "3.3"

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - $MARRTINOROBOT2_HOME/www:/usr/share/nginx/html
   
 


networks:
  default:
    name: marrtinorobot2-network

