version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - "${MARRTINOROBOT2_APPS}/www:/usr/share/nginx/html"
    networks:
      - nginx-network

  marrtinorobot2: 
    image: marrtinorobot2:system
    build:
      context: $MARRTINOROBOT2_HOME/docker
      dockerfile: Dockerfile.system
    container_name: system
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - ROS_IP=$ROS_IP
    volumes:
    - /dev:/dev
    - $MARRTINOROBOT2_HOME:/home/robot/src/marrtinorobot2


networks:
  nginx-network:
    driver: bridge
