joy_node:
  ros__parameters:
    device_id: 0  # L'indice del dispositivo, di solito 0 per il primo joystick
    deadzone: 0.05  # Imposta la zona morta per l'asse
    autorepeat_rate: 20.0  # Frequenza di ripetizione per i pulsanti tenuti premuti
    coalesce_interval: 0.001  # Intervallo per il raggruppamento degli eventi
    default_trig_val: True  # Utilizzato per alcuni controller
    use_dev_param: true  # Usare il parametro dev per indicare il dispositivo
    dev: /dev/input/js0  # Il dispositivo del joystick (può essere modificato se necessario)


