teleop_twist_joy_node:
  ros__parameters:
    # Asse per lo spostamento lineare avanti/indietro (secondo asse)
    axis_linear: 1  
    scale_linear: 1.0  # Scala per la velocità lineare
    scale_linear_turbo: 1.5  # Scala per la modalità turbo
    deadzone: 0.1  # Zona morta per evitare piccoli movimenti accidentali

    # Asse per la rotazione destra/sinistra (primo asse)
    axis_angular: 0  
    scale_angular: 1.0  # Scala per la velocità angolare
    scale_angular_turbo: 1.5  # Scala per la modalità turbo

    enable_button: 5  # L1 per abilitare il controllo
    enable_turbo_button: 6  # R1 per abilitare la modalità turbo
